[project]
name = "countdown"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask==3.1.3",
    "gpiozero>=2.0.1.post3",
    "np>=1.0.2",
    "numpy>=2.5.3",
    "pathlib>=1.0.1",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pydantic-tfl-api>=3.1.0",
    "pyowm>=3.5.0",
    "pytest-mock>=3.15.1",
    "requests>=2.32.5",
    "spidev>=3.8; sys_platform == 'linux'",
    "spotipy>=2.26.0",
]

[project.scripts]
countdown = "countdown:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstrument>=5.1.3",
    "pytest>=8.4.2",
    "pytest-cov>=7.1.0",
    "responses>=0.26.3",
]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
skip_empty = true

