[project]
name = "countdown-standalone"
version = "0.4.2"
requires-python = ">=3.12"
dependencies = [
    "countdown-core",
    "spidev>=3.8; sys_platform == 'linux'",
    "gpiozero>=2.0.1.post3",
    "lgpio>=0.2.2.0; sys_platform == 'linux'",
]

[project.scripts]
countdown-standalone = "countdown_standalone.main:run"

[tool.uv.sources]
countdown-core = { workspace = true }

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
