[project]
name = "countdown-epd"
version = "0.4.2"
requires-python = ">=3.14"
dependencies = [
    "spidev>=3.8; sys_platform == 'linux'",
    "gpiozero>=2.0.1.post3",
    "lgpio>=0.2.2.0; sys_platform == 'linux'",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
